<a href="https://colab.research.google.com/github/azzammuhammad/tugas1/blob/main/tugas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tugas Pertemuan 2**

In [ ]:
import numpy as np

In [ ]:
angka = np.arange(11,36)
matriks = angka.reshape(5,5)

# Membuat Angka jadi Berwarna dengan warna-warna tertentu
def warna_angka(angka):
    if angka in [11, 13, 15, 21, 23, 25, 31, 33, 35] :
      return "\033[32m{}\033[0m".format(angka) #Warna Hijau
    elif angka in [12, 14] :
      return "\033[31m{}\033[0m".format(angka) #warna Merah
    elif angka in [16, 26] :
      return "\033[34m{}\033[0m".format(angka) #Warna Biru
    elif angka in [12, 17, 22, 22, 27, 32] :
      return "\033[91m{}\033[0m".format(angka) #Warna Merah Muda
    else :
      return str(angka)

# Mengubah dengan warna angka yang sudah di rubah
matriks_warna = np.vectorize(warna_angka)(matriks)

# Menampilkan matriks
for baris in matriks_warna :
  print(" ".join(baris))


11 12 13 14 15
16 17 18 19 20
21 22 23 24 25
26 27 28 29 30
31 32 33 34 35


# **Numpy**

NumPy (singkatan dari Numerical Python) menyediakan antarmuka yang
efisien untuk menyimpan dan beroperasi pada buffer data yang padat. Dalam
beberapa hal, Array NumPy seperti tipe daftar bawaan Python, tetapi array
NumPy menyediakan banyak hal penyimpanan dan operasi data yang lebih
efisien karena ukuran array semakin besar.

In [ ]:
pip install numpy

In [ ]:
import numpy
numpy.__version__

'1.25.2'

In [ ]:
import numpy as np


In [ ]:
#membuat array
df = np.array([1,2,3])
df

array([1, 2, 3])

# **Type()**

Untuk pengecekan tipe pada data array menggunakan fungsi type()

In [ ]:
#mengecek tupe data array
type(df)

numpy.ndarray

In [ ]:
df1 = np.array([1,2,3])
df1.dtype

dtype('int64')

In [ ]:
df = np.array([1,2,3], dtype='int32')
df.dtype

dtype('int32')

**Array 2 dimensi**

In [ ]:
#multi dimensi array
my_array = np.array([[1,2,3,4,5], [2,4,6,8,10]])
my_array

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

**Membuat Array**

Dimulai dengan mendefinisikan tiga acak array: array satu dimensi, dua
dimensi, dan tiga dimensi. Dengan menggunakan Generator nomor acak
NumPy, akan di-seed dengan nilai yang ditetapkan untuk pastikan bahwa array
acak yang sama dihasilkan setiap kali kode ini dijalankan

In [ ]:
np.random.seed(0)
x1 = np.random.randint(10, size = 6) #one dimension array
x2 = np.random.randint(10, size = (3,4)) #two dimension array
x3 = np.random.randint(10, size=(3,4,5)) #three dimension array

print(f"x3 ndim : {x3.ndim}")
print(f"x3 ndim : {x3.shape}")
print(f"x3 ndim : {x3.size}")

x3 ndim : 3
x3 ndim : (3, 4, 5)
x3 ndim : 60


In [ ]:
arr_A = np.array([1,2,3,4,5])
arr_B = np.array([2,2,2,2,2])

print(f"Penjumlahan : {arr_A + arr_B}")
print(f"Pengurangan : {arr_A - arr_B}")
print(f"Perkalian : {arr_A * arr_B}")
print(f"Pembagian : {arr_A / arr_B}")
print(f"Perpangkatan : {arr_A ** arr_B}")

Penjumlahan : [3 4 5 6 7]
Pengurangan : [-1  0  1  2  3]
Perkalian : [ 2  4  6  8 10]
Pembagian : [0.5 1.  1.5 2.  2.5]
Perpangkatan : [ 1  4  9 16 25]


# **Slicing**

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [ ]:
x[5:] #element after index 5

array([5, 6, 7, 8, 9])

In [ ]:
x[4:6] #middle subarray

array([4, 5])

# **Manipulasi Shape**
Jenis operasi lain yang berguna adalah membentuk kembali array. Cara
yang paling fleksibel untuk melakukan ini adalah dengan metode reshape().
Misalnya, jika ingin memasukkan nomor 1 sampai 9 dalam kotak 3×3, dapat
melakukan hal berikut

In [ ]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1,2,3])


In [ ]:
grid = np.arange(11,36).reshape((5,5))
print(grid)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
